name: OtpAuthenticator
options:
  bundleIdPrefix: com.otpauthenticator
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "15.0"
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: NO

configs:
  Debug: debug
  Release: release

targets:
  # iOS App
  OtpAuthenticator-iOS:
    type: application
    platform: iOS
    sources:
      - path: OtpAuthenticator
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.otpauthenticator.app
        INFOPLIST_FILE: OtpAuthenticator/Info.plist
        CODE_SIGN_ENTITLEMENTS: OtpAuthenticator/OtpAuthenticator.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_NAME: OTP Authenticator
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Automatic
        ENABLE_DEBUG_DYLIB: NO
    dependencies:
      - target: OtpWidgetExtension-iOS
        embed: true

  # macOS App
  OtpAuthenticator-macOS:
    type: application
    platform: macOS
    sources:
      - path: OtpAuthenticator
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.otpauthenticator.app
        INFOPLIST_FILE: OtpAuthenticator/Info.plist
        CODE_SIGN_ENTITLEMENTS: OtpAuthenticator/OtpAuthenticator.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_NAME: OTP Authenticator
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Automatic
        ENABLE_DEBUG_DYLIB: NO
    dependencies:
      - target: OtpWidgetExtension-macOS
        embed: true

  # iOS Widget Extension
  OtpWidgetExtension-iOS:
    type: app-extension
    platform: iOS
    sources:
      - path: OtpWidgetExtension
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.otpauthenticator.app.widget
        INFOPLIST_FILE: OtpWidgetExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: OtpWidgetExtension/OtpWidgetExtension.entitlements
        PRODUCT_NAME: OtpWidget
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SKIP_INSTALL: YES
        CODE_SIGN_STYLE: Automatic

  # macOS Widget Extension
  OtpWidgetExtension-macOS:
    type: app-extension
    platform: macOS
    sources:
      - path: OtpWidgetExtension
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.otpauthenticator.app.widget
        INFOPLIST_FILE: OtpWidgetExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: OtpWidgetExtension/OtpWidgetExtension.entitlements
        PRODUCT_NAME: OtpWidget
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SKIP_INSTALL: YES
        CODE_SIGN_STYLE: Automatic

schemes:
  OtpAuthenticator-iOS:
    build:
      targets:
        OtpAuthenticator-iOS: all
        OtpWidgetExtension-iOS: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  OtpAuthenticator-macOS:
    build:
      targets:
        OtpAuthenticator-macOS: all
        OtpWidgetExtension-macOS: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
